### ISSUE TITLE
Dijkstra's Algorithm,  Null Pointer Exception. Added stack trace in description.  

### ISSUE THREAD

**Issue by RAHILKHERA** [RAHILKHERA/Graph#1]
java.lang.NullPointerException: Cannot invoke "java.util.List.clear()" because "path" is null
        at com.rahilakhera.graph.singlesourceshortestpath.Dijkstras.findShortestPath(Dijkstras.java:78)
        at com.rahilakhera.graph.singlesourceshortestpath.DijkstrasTest.testDijkstraAlgorithm(DijkstrasTest.java:27)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

**Comment by RAHILKHERA** [comment]
Fixed.  Modified Edge and Graph class.
